name: AWS example workflow
on:
  push
env:
  AWS_REGION : ${{secrets.AWS_REGION}}

permissions:
  id-token: write

jobs:
  CreateIAMPolicy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          role-session-name: ReadOnlyRole
          aws-region: ${{env.AWS_REGION}}
      - run: aws sts get-caller-identity
      - name:  Create IAM Policy files
        run: |
          sh ./CreateIAMPolicy.sh
