name: Check the IAM Policy workflow
on:
  push
env:
  AWS_REGION : ${{secrets.AWS_REGION}}

permissions:
  id-token: write

jobs:
  CreateIAMPolicy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install setupup tools
        run: pip install --user --upgrade setuptools wheel twine 
      - name: Increment version
        run: python ./inc_version.py
      - name:  Create tar.gz files and whl files
        run: |
          python ./setup.py sdist bdist_wheel
      - name: Archive Upload files
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
      - name: Upload test pypi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
        run: |
          python -m twine upload --repository testpypi dist/*
      - name: Install cfn-giam from test pypi
        run: |
          pip install -i https://test.pypi.org/simple/cfngiam
      - name: Check version cfn-giam from test pypi
        run: |
          cfn-giam -v
